spring:
  application:
    name: enicare

  datasource:
    url: jdbc:mysql://localhost:3306/enicare?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hamzaouisarra8@gmail.com
    password: nugq vmmy hqwa uesk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082
